version: '3'
 
services:
  database:
    container_name: database-notification
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
    
  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq-notification
   ports:
     - "5672:5672"
     - "15672:15672"
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq

  loki:
    container_name: loki-notification
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=etc/loki/local-config.yaml

  grafana:
    container_name: grafana-notification
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  pgdata:
    driver: local
  rabbitmq_data:
  grafana-storage:
