version: '3'

services:
  database:
    container_name: database-notification
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=notification
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
    
  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq-notification
   ports:
     - "5672:5672"
     - "15672:15672"
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq

volumes:
  pgdata:
    driver: local
  rabbitmq_data:
